import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SITE_URL } from "@/lib/constants";
import PageTransition from "@/components/layout/page-transition";
import { Navbar } from "@/components/layout/sticky-navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "michaeltrannhan's portfolio",
    template: `%s | michaeltrannhan's portfolio`,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-video-preview": -1,
      "max-snippet": -1,
    },
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PageTransition>
          <main className="w-full min-h-screen relative">
            <Navbar />
            {children}
          </main>
        </PageTransition>
      </body>
    </html>
  );
}
